#Build settings
gems:
  - jekyll-assets
  - jekyll-cloudinary
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-autoprefixer
  - breakpoint

include:
  - _pages
  - _img
  - .htaccess

exclude:
  - node_modules
  - README.md
  - LICENSE.md
  - Gemfile*
  - uninstall all gems.txt
  - Netlify CMS.md
  - Rakefile*
  - style.css
  - package.json
  - gulpfile.js
  - font-awesome.scss
  - ignore

markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  -
    scope:
      path: ""
    values:
      image: https://res.cloudinary.com/krvmedia/img/blog-image.jpg
  
#Site settings
collections: 
  
title: UNZA UCS
email: 
description: > # this means to ignore newlines until "baseurl:"
  The Univeristy of Zambia Computer Society.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000"
logo: 
type: website

excerpt_separator: <!--more-->
permalink: /:year/:month/:slug
timezone: Africa/Lusaka
jekyll-mentions: https://twitter.com

#HTML compress
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
  blanklines : true

#Assets
sass:
  sass_dir: _sass
  css_dir: css
  style:  expanded
  autoprefixer:
      browsers: ["last 5 versions","> 5%","ie > 6", "Edge"]
      
assets:
  compress:
    css: false
    js: false
  cache: .asset-cache
  cache_type: filesystem
  prefix: "/assets"
  digest: false
  sources:
    - "_assets/js"
  features:
    liquid: false
    integrity: false
    automatic_img_size: true 
    automatic_img_alt : true 
  gzip: [ text/css, application/javascript ]

#Cloudinary
cloudinary:
  cloud_name: krvmedia
  verbose: true
  presets:
    presets:
    default:
      min_width: 320
      max_width: 1920
      fallback_max_width: 800
      steps: 6
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    logo:
      min_width: 80
      max_width: 400
      fallback_max_width: 200
      steps: 3
      sizes: '(min-width: 50rem) 13rem, (min-width: 40rem) 25vw, 45vw'
      figure: never
      attributes:
        class: logo
